/**
 * index.ts — Tauri IPC 适配层（Solid 响应式封装）。
 *
 * 将 frontend/src/bridge.ts 的 23+ 个 Tauri command 包装为 Solid resource/hook。
 * 数据流：组件 → 本层 hook → bridge.ts invoke → Rust command。
 * 事件流：submit_prompt 的 Channel 经 bus.ts 信号总线分发。
 *
 * 说明：与 opencode 的 HTTP SDK 不同，本桌面端全部数据访问走 Tauri IPC，
 * 因此这里是对既有 bridge.ts 的薄封装，不引入任何 opencode 客户端。
 */

export * from "./bus";
export * from "./session";
// 复用既有 bridge.ts 的 invoke 封装（命令名与参数契约不变）
export {
  submitPrompt,
  cancelRun,
  newSession,
  healthCheck,
  listSessions,
  createSession,
  deleteSession,
  renameSession,
  listSkills,
  listProviders,
  getConfig,
  getCapabilities,
  getWorkspaceFiles,
  getFileDiff,
  respondApproval,
  getSandboxConfig,
  setSandboxConfig,
  getNetworkConfig,
  setNetworkConfig,
  networkDiagnostics,
  getPermissions,
  setPermissionRule,
  getHooks,
  setHook,
  deleteHook,
  listMcpServers,
  addMcpServer,
  removeMcpServer,
  toggleMcpServer,
  listSubagents,
  getOrchProgress,
  runDiagnostics,
  getBillingStats,
  getWikiPages,
  getKnowledgeCards,
  getMemories,
  addMemory,
  deleteMemory,
  saveSettings,
  loadSettings,
  getSystemPrompt,
  setSystemPrompt,
  getReasoningParams,
  setReasoningParams,
  listTools,
  setToolEnabled,
  getLogConfig,
  setLogConfig,
  exportLogs,
  getChangedFiles,
  acceptFileChange,
  rejectFileChange,
  listWorktrees,
  switchWorktree,
  getTriggers,
  setTriggers,
  getShortcuts,
  checkForUpdates,
  listTabs,
  createTab,
  closeTab,
  type SessionInfo,
  type SandboxConfig,
  type NetworkConfig,
  type PermissionRule,
  type Hook,
  type McpServer,
  type SubAgent,
  type ReasoningParams,
  type ToolInfo,
  type LogConfig,
  type ScheduleEntry,
  type TriggerConfig,
  type TabInfo,
  type EventHandlers,
} from "../bridge.ts";