use anyhow::Context;
use std::io::{BufRead, Write};
use std::path::PathBuf;

/// Run the interactive configuration wizard.
/// Asks a few questions and writes a dpronix.toml to the current directory.
pub async fn run_setup_wizard(local: bool) -> anyhow::Result<()> {
    let stdin = std::io::stdin();
    let mut reader = std::io::BufReader::new(stdin.lock());

    println!();
    println!("╭────────────────────────────────────────╮");
    println!("│     dpronix setup wizard              │");
    println!("╰────────────────────────────────────────╯");
    println!();

    // Provider kind
    println!("Which AI provider do you want to use?");
    println!("  [1] DeepSeek (default)");
    println!("  [2] OpenAI");
    println!("  [3] Anthropic");
    println!("  [4] OpenRouter");
    println!("  [5] Ollama (local)");
    print!("> ");
    std::io::stdout().flush().ok();

    let mut choice = String::new();
    reader.read_line(&mut choice)?;
    let choice = choice.trim();

    let (kind, default_base_url, default_model, api_key_env) = match choice {
        "2" => (
            "openai",
            "https://api.openai.com/v1",
            "gpt-4o",
            "OPENAI_API_KEY",
        ),
        "3" => (
            "anthropic",
            "https://api.anthropic.com",
            "claude-sonnet-5-20251001",
            "ANTHROPIC_API_KEY",
        ),
        "4" => (
            "openai",
            "https://openrouter.ai/api/v1",
            "anthropic/claude-sonnet-5",
            "OPENROUTER_API_KEY",
        ),
        "5" => ("openai", "http://localhost:11434/v1", "llama3.2", "OLLAMA"),
        _ => (
            "openai",
            "https://api.deepseek.com",
            "deepseek-chat",
            "DEEPSEEK_API_KEY",
        ),
    };

    // API key
    print!("API key environment variable name [default: {api_key_env}]: ");
    std::io::stdout().flush().ok();
    let mut key_env = String::new();
    reader.read_line(&mut key_env)?;
    let key_env = key_env.trim();
    let key_env = if key_env.is_empty() {
        api_key_env
    } else {
        key_env
    };

    // Model name
    print!("Model name [default: {default_model}]: ");
    std::io::stdout().flush().ok();
    let mut model = String::new();
    reader.read_line(&mut model)?;
    let model = model.trim();
    let model = if model.is_empty() {
        default_model
    } else {
        model
    };

    // Max steps
    print!("Max tool-call rounds per turn [default: 10]: ");
    std::io::stdout().flush().ok();
    let mut max_steps = String::new();
    reader.read_line(&mut max_steps)?;
    let max_steps: usize = max_steps.trim().parse().unwrap_or(10);

    // Permission mode
    println!();
    println!("Permission mode for write tools:");
    println!("  [1] Ask (prompt before executing — recommended)");
    println!("  [2] Allow (auto-approve all write tools)");
    println!("  [3] Deny (block all write tools)");
    print!("> ");
    std::io::stdout().flush().ok();
    let mut perm = String::new();
    reader.read_line(&mut perm)?;
    let perm_mode = match perm.trim() {
        "2" => "allow",
        "3" => "deny",
        _ => "ask",
    };

    // Generate config
    let config_path = if local {
        PathBuf::from("dpronix.toml")
    } else {
        let home = dirs::home_dir().context("cannot determine home directory")?;
        std::fs::create_dir_all(home.join(".dpronix"))?;
        home.join(".dpronix").join("config.toml")
    };

    let toml_content = format!(
        r#"# dpronix configuration — generated by setup wizard

default_model = "{model}"
default_max_steps = {max_steps}

[[providers]]
name = "{kind}"
kind = "{kind}"
base_url = "{default_base_url}"
model = "{model}"
api_key_env = "{key_env}"
timeout_secs = 120
max_retries = 3

[agent]
max_steps = {max_steps}
concurrent_tools = true

[permissions]
default_mode = "{perm_mode}"
"#
    );

    // Confirm
    println!();
    println!("─── Preview ───");
    println!("{toml_content}");
    println!("───────────────");
    println!();
    print!("Write to {}? [Y/n]: ", config_path.display());
    std::io::stdout().flush().ok();

    let mut confirm = String::new();
    reader.read_line(&mut confirm)?;
    if confirm.trim().to_lowercase() == "n" {
        println!("Aborted.");
        return Ok(());
    }

    std::fs::write(&config_path, toml_content)
        .with_context(|| format!("failed to write {}", config_path.display()))?;

    println!("✓ Config written to {}", config_path.display());
    println!();
    println!("Next: set your API key and run `dpronix run \"hello\"`");
    println!("  export {key_env}=your-key-here");

    Ok(())
}
